Controllers/ClientiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proiect_Cafenea.Data;
using Proiect_Cafenea.Models;

namespace Proiect_Cafenea.Controllers
{
    public class ClientiController : Controller
    {
        private readonly CafeneaDbContext _context;

        public ClientiController(CafeneaDbContext context)
        {
            _context = context;
        }

        // GET: Clienti
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentFilter"] = searchString;

            var clienti = from c in _context.Clienti select c;


            if (!String.IsNullOrEmpty(searchString))
            {
                clienti = clienti.Where(s => s.Nume.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    clienti = clienti.OrderByDescending(s => s.Nume);
                    break;
                default:
                    clienti = clienti.OrderBy(s => s.Nume);
                    break;
            }
            return View(await clienti.AsNoTracking().ToListAsync());
        }


        // GET: Clienti/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clienti
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clienti/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clienti/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nume,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clienti/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clienti.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clienti/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nume,Email")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clienti/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clienti
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clienti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clienti.FindAsync(id);
            if (client != null)
            {
                _context.Clienti.Remove(client);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clienti.Any(e => e.Id == id);
        }
    }
}

Controllers/ComenziController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Proiect_Cafenea.Data;
using Proiect_Cafenea.Models;

namespace Proiect_Cafenea.Controllers
{
    public class ComenziController : Controller
    {
        private readonly CafeneaDbContext _context;

        public ComenziController(CafeneaDbContext context)
        {
            _context = context;
        }

        // GET: Comenzi
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            var comenziQuery = _context.Comenzi.Include(c => c.Client).AsQueryable();
            switch (sortOrder) //sorteaza comenzile
            {
                case "date_desc":

                    comenziQuery = comenziQuery.OrderByDescending(c => c.DataComanda);
                    break;
                default:
                    comenziQuery = comenziQuery.OrderBy(c => c.DataComanda);
                    break;
            }
            return View(await comenziQuery.AsNoTracking().ToListAsync());
        }



        // GET: Comenzi/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comanda = await _context.Comenzi
                .Include(c => c.Client)
                .Include(c => c.Detalii)                      
                     .ThenInclude(d => d.Produs)                      
                .FirstOrDefaultAsync(m => m.Id == id);
                
            if (comanda == null)
            {
                return NotFound();
            }

            return View(comanda);
        }







        // GET: Comenzi/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clienti, "Id", "Nume");
            return View();
        }

        // POST: Comenzi/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DataComanda,ClientId")] Comanda comanda)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comanda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clienti, "Id", "Nume", comanda.ClientId);
            return View(comanda);
        }

        // GET: Comenzi/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comanda = await _context.Comenzi.FindAsync(id);
            if (comanda == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clienti, "Id", "Nume", comanda.ClientId);
            return View(comanda);
        }

        // POST: Comenzi/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DataComanda,ClientId")] Comanda comanda)
        {
            if (id != comanda.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comanda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComandaExists(comanda.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clienti, "Id", "Nume", comanda.ClientId);
            return View(comanda);
        }

        // GET: Comenzi/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comanda = await _context.Comenzi
                .Include(c => c.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comanda == null)
            {
                return NotFound();
            }

            return View(comanda);
        }

        // POST: Comenzi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comanda = await _context.Comenzi.FindAsync(id);
            if (comanda != null)
            {
                _context.Comenzi.Remove(comanda);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComandaExists(int id)
        {
            return _context.Comenzi.Any(e => e.Id == id);
        }
    }
}

Controllers/ProduseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proiect_Cafenea.Data;
using Proiect_Cafenea.Models;

namespace Proiect_Cafenea.Controllers
{
    public class ProduseController : Controller
    {
        private readonly CafeneaDbContext _context;

        public ProduseController(CafeneaDbContext context)
        {
            _context = context;
        }

        // GET: Produse
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PretSortParm"] = sortOrder == "Pret_Asc" ? "Pret_Desc" : "Pret_Asc";
            ViewData["CurrentFilter"] = searchString;
            var produse = _context.Produse.Include(p => p.Categorie).AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                string searchLower = searchString.ToLower();
                produse = produse.Where(s => s.Nume.ToLower().Contains(searchLower)
                                  || s.Categorie.Nume.ToLower().Contains(searchLower));
            }
            produse = sortOrder switch
            {
                "Pret_Asc" => produse.OrderBy(p => p.Pret),           
                "Pret_Desc" => produse.OrderByDescending(p => p.Pret),
                "name_desc" => produse.OrderByDescending(p => p.Nume),
                _ => produse.OrderBy(p => p.Nume)                      
            };
            return View(await produse.ToListAsync());
        }


        // GET: Produse/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produs = await _context.Produse
                .Include(p => p.Categorie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produs == null)
            {
                return NotFound();
            }

            return View(produs);
        }

        // GET: Produse/Create
        public IActionResult Create()
        {
            ViewData["CategorieId"] = new SelectList(_context.Categorii, "Id", "Nume");
            return View();
        }

        // POST: Produse/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nume,Pret,CategorieId")] Produs produs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategorieId"] = new SelectList(_context.Categorii, "Id", "Nume", produs.CategorieId);
            return View(produs);
        }

        // GET: Produse/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produs = await _context.Produse.FindAsync(id);
            if (produs == null)
            {
                return NotFound();
            }
            ViewData["CategorieId"] = new SelectList(_context.Categorii, "Id", "Nume", produs.CategorieId);
            return View(produs);
        }

        // POST: Produse/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nume,Pret,CategorieId")] Produs produs)
        {
            if (id != produs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdusExists(produs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategorieId"] = new SelectList(_context.Categorii, "Id", "Nume", produs.CategorieId);
            return View(produs);
        }

        // GET: Produse/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produs = await _context.Produse
                .Include(p => p.Categorie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produs == null)
            {
                return NotFound();
            }

            return View(produs);
        }

        // POST: Produse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produs = await _context.Produse.FindAsync(id);
            if (produs != null)
            {
                _context.Produse.Remove(produs);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdusExists(int id)
        {
            return _context.Produse.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cafenea Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <style>
     
        .sidebar-minimal {
            min-width: 80px;
            max-width: 80px;
            background-color: #1a1a1a; 
            color: white;
            height: 100vh;
            position: fixed;
            transition: all 0.3s ease;
            z-index: 1000;
            overflow: hidden;
        }

       
            .sidebar-minimal:hover {
                min-width: 240px;
                max-width: 240px;
                box-shadow: 10px 0 20px rgba(0,0,0,0.3);
            }

        .logo-section {
            padding: 20px;
            white-space: nowrap;
            border-bottom: 1px solid #343a40;
            display: flex;
            align-items: center;
            overflow: hidden;
        }

        .logo-icon {
            font-size: 1.5rem;
            margin-right: 20px;
        }

        .logo-text {
            font-family: 'Playfair Display', serif;
            font-weight: 800;
            font-size: 1.2rem;
            opacity: 0;
            transition: 0.3s;
        }

        .sidebar-minimal:hover .logo-text {
            opacity: 1;
        }

        .sidebar-link {
            color: #adb5bd;
            text-decoration: none;
            padding: 15px 25px;
            display: flex;
            align-items: center;
            transition: 0.3s;
            white-space: nowrap;
        }

            .sidebar-link i {
                font-size: 1.4rem;
                min-width: 30px;
                margin-right: 25px;
            }

        .link-text {
            opacity: 0;
            transition: 0.3s;
        }

        .sidebar-minimal:hover .link-text {
            opacity: 1;
        }

      
        .sidebar-link:hover {
            background-color: #3e2723;
            color: #A65E2E; 
        }

        .sidebar-link.active {
            background-color: #3e2723;
            color: white;
            border-left: 4px solid #A65E2E;
        }

      
        main {
            margin-left: 80px;
            background-color: #f8f9fa;
            min-height: 100vh;
            transition: margin-left 0.3s ease;
        }

        
        .sidebar-minimal:hover ~ main {
            margin-left: 240px;
        }
    </style>
</head>
<body>
    <div class="container-fluid px-0">
        <div class="d-flex">
            <nav class="sidebar-minimal d-none d-md-block">
                
                <div class="nav flex-column mt-2">
                    <a class="sidebar-link @(ViewContext.RouteData.Values["Controller"]?.ToString() == "Home" && ViewContext.RouteData.Values["Action"]?.ToString() == "Index" ? "active" : "")"
                       asp-controller="Home" asp-action="Index">
                        <i class="bi bi-speedometer2"></i>
                        <span class="link-text">Dashboard</span>
                    </a>
                    <a class="sidebar-link" asp-controller="Categorii" asp-action="Index">
                        <i class="bi bi-tags"></i>
                        <span class="link-text">Categorii</span>
                    </a>
                    <a class="sidebar-link" asp-controller="Produse" asp-action="Index">
                        <i class="bi bi-cup-hot"></i>
                        <span class="link-text">Produse</span>
                    </a>
                    <a class="sidebar-link" asp-controller="Clienti" asp-action="Index">
                        <i class="bi bi-people"></i>
                        <span class="link-text">Clienți</span>
                    </a>
                    <a class="sidebar-link" asp-controller="Comenzi" asp-action="Index">
                        <i class="bi bi-cart-check"></i>
                        <span class="link-text">Comenzi</span>
                    </a>
                    <a class="sidebar-link" asp-controller="DetaliiComenzi" asp-action="Index">
                        <i class="bi bi-list-check"></i>
                        <span class="link-text">Detalii Comenzi</span>
                    </a>
                    <a class="sidebar-link" asp-controller="Recomandari" asp-action="Index">
                        <i class="bi bi-magic"></i>
                        <span class="link-text">Recomandări</span>
                    </a>
                    <hr class="mx-3" style="border-top: 1px solid #444;">
                    <a class="sidebar-link" asp-controller="Home" asp-action="Privacy">
                        <i class="bi bi-shield-lock"></i>
                        <span class="link-text">Privacy</span>
                    </a>

                </div>
            </nav>

            <main class="flex-grow-1 px-md-4">
                <div class="pt-4 pb-3">
                    @RenderBody()
                </div>

                <footer class="pt-5 pb-4 text-muted border-top mt-5 text-center">
                    &copy; 2026 - Sistem de gestiune
                </footer>
            </main>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>